-- 코드를 입력하세요
# SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(ONLINE_SALE.USER_ID) AS USERS
# FROM USER_INFO JOIN ONLINE_SALE ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
# WHERE GENDER IS NOT NULL
# GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
# ORDER BY YEAR, MONTH, GENDER

SELECT YEAR, MONTH, GENDER, COUNT(DISTINCT(USERS))AS USERS
FROM (
    SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, ONLINE_SALE.USER_ID AS USERS
    FROM USER_INFO JOIN ONLINE_SALE ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
    WHERE GENDER IS NOT NULL) AS T
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER