-- 코드를 입력하세요
# 2021년 가입 회원 상픔 구매 회원 수/2021년에 가입한 전체 회원 JOIN ONLINE_SALE ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID COUNT(SALES_DATE IS NOT NULL), COUNT(SALES_DATE)
# YEAR(SALES_DATE), MONTH(SALES_DATE),COUNT(SALES_DATE), COUNT(*)
# 2021년에 가입한 회원
# SELECT YEAR(SALES_DATE), MONTH(SALES_DATE), COUNT(SALES_DATE)
# FROM USER_INFO LEFT JOIN ONLINE_SALE ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
# WHERE YEAR(JOINED) = 2021 AND YEAR(SALES_DATE) IS NOT NULL AND MONTH(SALES_DATE) IS NOT NULL
#     AND SALES_DATE IS NOT NULL
# GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
# ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)

# SELECT *
# FROM (
#     SELECT *
#     FROM USER_INFO LEFT JOIN ONLINE_SALE ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
#     WHERE YEAR(JOINED) = 2021
#     ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)
#     ) AS T

SELECT YEAR(SALES_DATE), MONTH(SALES_DATE), COUNT(DISTINCT(USER_INFO.USER_ID)) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT(USER_INFO.USER_ID)) / 
    (SELECT COUNT(DISTINCT(USER_INFO.USER_ID))
    FROM USER_INFO LEFT JOIN ONLINE_SALE ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
    WHERE YEAR(JOINED) = 2021),1) AS PUCHASED_RATIO

FROM USER_INFO JOIN ONLINE_SALE ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)
