-- 코드를 입력하세요
# SELECT HOUR(DATETIME) AS HOUR, COUNT(*)
# FROM ANIMAL_OUTS
# GROUP BY HOUR(DATETIME)
# ORDER BY HOUR
SET @HOUR = -1;

SELECT (@HOUR := @HOUR +1) AS HOUR,
    (SELECT COUNT(*)
     FROM ANIMAL_OUTS
     WHERE HOUR(DATETIME) = @HOUR
    ) AS COUNT
FROM ANIMAL_OUTS
WHERE @HOUR < 23;
# SET @HOUR = -1;
# SELECT (@HOUR := @HOUR +1) AS HOUR,
#     (SELECT COUNT(HOUR(DATETIME)) 
#     FROM ANIMAL_OUTS 
#     WHERE HOUR(DATETIME)=@HOUR) AS COUNT 
#     FROM ANIMAL_OUTS
# WHERE @HOUR < 23;