-- 코드를 입력하세요
SELECT M1.MEMBER_NAME,	REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,"%Y-%m-%d")
FROM MEMBER_PROFILE AS M1 JOIN REST_REVIEW AS R1 ON M1.MEMBER_ID = R1.MEMBER_ID
WHERE M1.MEMBER_ID = (
SELECT M.MEMBER_ID
FROM MEMBER_PROFILE AS M JOIN REST_REVIEW AS R ON M.MEMBER_ID = R.MEMBER_ID
GROUP BY M.MEMBER_ID
ORDER BY COUNT(*) DESC
LIMIT 1 )
ORDER BY REVIEW_DATE,REVIEW_TEXT ASC;