-- 코드를 작성해주세요
# SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH), FISH_TYPE
# FROM(
#     SELECT FISH_TYPE, IFNULL(LENGTH, 10) AS LENGTH
#     FROM FISH_INFO) AS T
# WHERE LENGTH>=33
# GROUP BY FISH_TYPE
# ORDER BY FISH_TYPE

# SELECT FISH_COUNT, MAX(LENGTH)AS MAX_LENGTH, FISH_TYPE
# FROM FISH_INFO
# WHERE FISH_TYPE IN 
SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
WHERE FISH_TYPE IN (
    SELECT FISH_TYPE
    FROM(
        SELECT COUNT(*) AS FISH_COUNT, FISH_TYPE, AVG(IFNULL(LENGTH, 10)) AS LENGTH
        FROM FISH_INFO
        GROUP BY FISH_TYPE
        HAVING LENGTH>=33) AS T
    )
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE